# -*- coding: utf-8 -*-
"""age-quiz.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mqA9fLkOCT-B8TrtpjWsL238dAJJO0Xo
"""

# Practical Task 1

age = int(input("Please enter your age: "))

if age > 100:
    print ("Sorry, you're dead.")
elif age >= 65:
    print ("Enjoy your retirement!")
elif age >= 40:
    print ("You're over the hill.")
elif age == 21:
    print ("Congrats on your 21st!")
elif age < 13:
    print ("You qualify for the kiddie discount.")
else:
    print ("Age is but a number.")